- hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - fetch_mods
  vars:
    download_dir: "{{ playbook_dir }}/fetched_addons"

- hosts: dev
  gather_facts: False
  roles:
    - install_msm
    - { role: create_instances, type: 'example', nr: '2', start_port: 27015}