---
- name: create instance
  command: csgo-server @{{ instance_name }} create

- name: copy base conf
  template:
      src: '{{ item }}.j2'
      dest: '{{ conf_dir }}/{{ item }}'
  with_items: ['server.conf','gotv.conf']

- name: copy base csgo folder
  synchronize:
      src: '{{ playbook_dir }}/cfgs/base/csgo'
      dest: '{{ instance_dir }}'

- name: check if mm sm required
  stat:
    path: '{{ playbook_dir }}/cfgs/{{ type }}/sm'
  register: st
  delegate_to: localhost

- name: copy mm and sm if required
  synchronize:
      src: '{{ playbook_dir }}/fetched_addons/'
      dest: '{{ instance_dir }}/csgo/'
  when: st.stat.exists

- name: copy type name.cfg
  template:
      src: '{{ playbook_dir }}/cfgs/{{ type }}/name.cfg.j2'
      dest: '{{ instance_dir }}/csgo/cfg/name.cfg'

- name: copy type csgo folder
  synchronize:
      src: '{{ playbook_dir }}/cfgs/{{ type }}/csgo'
      dest: '{{ instance_dir }}'